### ISSUE TITLE
OnServerInitialized invoked 2 times in HurtWorld

### ISSUE THREAD

**Issue by Bombardir** [OxideMod/Oxide#970] opened 2016-12-27 20:16 UTC
On server startup this hook (OnServerInitialized) can be called 2 times, especially with reload of plugin

**Comment by lukespragg** [comment] 2016-12-27 20:17
Is it called two times when the server is first loaded? It being called when a plugin is loaded is as designed.

**Comment by Bombardir** [comment] 2016-12-27 20:22
Yes on first load, even without reload command.

**Comment by Mughisi** [comment] 2017-01-04 11:43
@Bombardir is it possible to provide us with a log file and the plugins to reproduce this issue as I can't seem to be able to reproduce the hook being called twice.

**Comment by lukespragg** [comment] 2017-01-11 01:17
Closing for now as we can't reproduce it. Let us know if you have a test case and plugin for us. :)

**Closed by lukespragg** 2017-01-11 01:17 UTC
