### ISSUE TITLE
Brackets in username cause errors

### ISSUE THREAD

**Issue by ReptiDK** [OxideMod/Oxide#418] opened 2015-06-19 18:49 UTC
I think there's an error in Oxide, when players have brackets { } in their names: Got the following error from the Give-plugin when I try to give something to a player with brackets in his name:
```
[6/19/2015 12:50:28 PM] [Oxide] 12:50 PM [Info] [Give] GIVE: ReptiDK used inv.giveplayer Major apple 1
[6/19/2015 12:50:28 PM] [Oxide] 12:50 PM [Debug]   at System.String.ParseFormatSpecifier (System.String str, System.Int32& ptr, System.Int32& n, System.Int32& width, System.Boolean& left_align, System.String& format) [0x00000] in <filename unknown>:0 
  at System.String.FormatHelper (System.Text.StringBuilder result, IFormatProvider provider, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.String.Format (IFormatProvider provider, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.String.Format (System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at Oxide.Plugins.RustPlugin.SendReply (.Arg arg, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at Oxide.Plugins.Give.SendTheReply (System.Object source, System.String message) [0x00000] in <filename unknown>:0 
  at Oxide.Plugins.Give.GivePlayer (System.Object source, System.String[] Args) [0x00000] in <filename unknown>:0 
  at Oxide.Plugins.Give.cmdConsoleGivePlayer (.Arg arg) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
```

Also tried the EasyHeal-plugin and some other plugins I wrote. Came around the problem using "Replace": 
```
private void OnPlayerInit(BasePlayer player){
     foreach (BasePlayer playerJoin in BasePlayer.activePlayerList){
          SendReply(playerJoin, "<color=" + textColor + ">" + player.displayName.Replace("{","{{").Replace("}","}}") + "</color> has joined the game!");
     }
}
```

Damn. Don't know how to write in here.

**Comment by Mughisi** [comment] 2015-06-19 19:16
Most likely caused by the string.Format that is available for the methods, we'll look into this.

**Comment by bawNg** [comment] 2015-07-17 02:04
A fix for this was included with the bug fixes I commited today before the Rust update was released.

**Closed by bawNg** 2015-07-17 02:04 UTC
